apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: snipe
spec:
  storageClassName: nfs-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2G


