apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: snipe-hpa
  namespace: snipe
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: snipe
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80

