apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-data-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10G
  nfs:
    server: 172.31.25.33
    path: /nfs/eks/nexus
    readOnly: false

