apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackbox
  namespace: grafana
spec:
  selector:
    matchLabels:
      app: blackbox
  template:
    metadata:
      labels:
        app: blackbox
    spec:
      volumes:
      - name: config
        configMap:
          name: blackbox
      containers:
      - name: blackbox
        image: prom/blackbox-exporter
        args:
        - "--config.file=/config/blackbox.yaml"
        resources:
          limits:
            memory: "128Mi"
            cpu: "64m"
        volumeMounts:
        - name: config
          mountPath: /config
        ports:
        - containerPort: 9115
---

apiVersion: v1
kind: Service
metadata:
  name: blackbox
  namespace: grafana
spec:
  type: ClusterIP
  selector:
    app: blackbox
  ports:
  - port: 9115
    targetPort: 9115


