apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cluster-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: contact@itsnoor.info
    privateKeySecretRef:
      name: letsencrypt-cluster-production
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: nginx
