apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-vol
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /volumes