apiVersion: v1
kind: Secret
metadata:
  name: db-secret
data:
  MYSQL_ROOT_PASSWORD: $(echo -n MYSQL_ROOT_PASSWORD | base64)
  MYSQL_USER: $(echo -n MYSQL_USER | base64)
  MYSQL_PASSWORD: $(echo -n MYSQL_PASSWORD | base64)
  mysql-server: $(echo -n db-svc | base64)
