apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nodejs-cert-prod
  namespace: istio-system
spec:
  secretName: nodejs-cert-prod
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - "micro.example.com"
  issuerRef:
    name: letsencrypt-prod-cluster
    kind: ClusterIssuer
    group: cert-manager.io
