apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: monitoring
spec:
  volumeName: grafana-pv      
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10G


