apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: metricbeat
  namespace: elk
spec:
  type: metricbeat
  version: 8.9.1
  config:
    metricbeat.modules:
    - module: nginx
      metricsets: ["stubstatus"]
      enabled: true
      period: 10s
      hosts: ["nginx-ingress-nginx-controller.nginx.svc"]
      server_status_path: "nginx_status"
    setup.template:
      name: "k8s-nginx-metricbeat-template"
      pattern: "k8s-nginx-metrics-*"
      enabled: false
    output.elasticsearch:
      hosts: ["https://monitoring-es-http:9200"]
      index: "k8s-nginx-metrics"
      username: "$username"
      password: "$password"
      ssl.certificate_authorities: "/certs/ca.crt"
  deployment:
    podTemplate:
      spec:
        containers:
        - args:
          - -e
          - -c
          - /etc/beat.yml
          name: metricbeat
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          volumeMounts:
          - name: cert
            mountPath: "/certs"
        dnsPolicy: ClusterFirstWithHostNet
        securityContext:
          runAsUser: 0
        volumes:
        - name: cert
          secret:
            secretName: monitoring-es-http-certs-public

