apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
  namespace: nginx
spec:
  volumeName: nginx-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi


