controller:
  config:
    use-forwarded-headers: "true"
    real-ip-header: "proxy_protocol"
    nginx-status-ipv4-whitelist: "all"
    watch-ingress-without-class: "true"
    log-format-escape-json: "false"
    log-format-upstream: '{"@timestamp": "$time_iso8601","host": "$hostname","server_ip": "$server_addr","client_ip": "$remote_addr","xff": "$http_x_forwarded_for","domain": "$host","url": "$uri","referer": "$http_referer","args": "$args","upstreamtime": "$upstream_response_time","responsetime": "$request_time","request_method": "$request_method","status": "$status","size": "$body_bytes_sent","request_body": "$request_body","request_length": "$request_length","protocol": "$server_protocol","upstreamhost": "$upstream_addr","file_dir": "$request_filename","http_user_agent": "$http_user_agent"}'
  
  nodeSelector:
    kubernetes.io/os: linux
  resources:
    requests:
      cpu: 100m
      memory: 90Mi
  
  extraVolumeMounts:
    - name: log
      mountPath: /var/log/nginx
  extraVolumes:
    - name: log
      persistentVolumeClaim:
         claimName: nginx-pvc

  service:
    enabled: true
    externalTrafficPolicy: "Local"
