apiVersion: v1
kind: PersistentVolume
metadata:
  name: pritunl-data-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  mountOptions:
  - hard
  - nfsvers=4.1
  nfs:
    path: /eks/pritunl-data
    server: 172.20.14.245

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pritunl-mongo-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  mountOptions:
  - hard
  - nfsvers=4.1
  nfs:
    path: /eks/pritunl-mongo
    server: 172.20.14.245
