apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pritunl-data-pvc
  namespace: pritunl
spec:
  volumeName: pritunl-data-pv
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pritunl-mongo-pvc
  namespace: pritunl
spec:
  volumeName: pritunl-mongo-pv
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
