apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: wordpress
data:
  my.cnf: |-
    [mysqld]
    slow_query_log = 1
    slow_query_log_file = /var/lib/mysql/slow_query.log
    long_query_time = 2
    innodb_buffer_pool_size = 268435456
    max_connections = 200
