apiVersion: v1
kind: Secret
metadata:
  name: wp-secret
  namespace: wordpress
type: Opaque
data:
  WORDPRESS_DB_HOST: ZGItc3Zj
  WORDPRESS_DB_NAME: d3AtZGI=
  WORDPRESS_DB_USER: YWRtaW4=
  WORDPRESS_DB_PASSWORD: MTIzNA==
