apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-vc
  namespace: wordpress
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1G
  volumeName: pv01
