apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonar-log-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.50.104
    path: /nfs/sonarqube-log-pv

