apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-ext-pvc
  namespace: sonarqube

spec:
  volumeName: sonar-ext-pv     
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1G
 

