apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-log-pvc
  namespace: sonarqube
spec:
  volumeName: sonar-log-pv 
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1G
 

