apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-data-pvc
  namespace: sonarqube

spec:
  volumeName: sonar-data-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1G
 

