apiVersion: v1
kind: ConfigMap
metadata:
  name: falco-logrotate-config
  namespace: falco
data:
  falco: |
    /var/log/falco.log {
        daily
        rotate 7
        compress
        missingok
        notifempty
        copytruncate
    }

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: falco-logrotate
  namespace: falco
spec:
  schedule: "0 * * * *"  # hourly
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: logrotate
            image: 32xxxxxxxxx.dkr.ecr.ap-south-1.amazonaws.com/ggg/logrotate:latest
            args:
              - "-s"
              - "/var/lib/logrotate/logrotate.status"
              - "/etc/logrotate.d"
            volumeMounts:
              - name: log-dir
                mountPath: /var/log
              - name: rules
                mountPath: /etc/logrotate.d
              - name: state
                mountPath: /var/lib/logrotate
          restartPolicy: OnFailure
          volumes:
            - name: log-dir
              hostPath:
                path: /var/log
                type: Directory
            - name: rules
              configMap:
                name: falco-logrotate-config
            - name: state
              emptyDir: {}

