apiVersion: v1
kind: PersistentVolume
metadata:
  name: vas-pv
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.10   
    path: /nfs/vas


